// Generates docs/ONTOLOGY.md from the canonical ontology in src/lib/ontology.
//
// Run with: npm run gen:ontology
//
// The output is auto-generated — edit the domain modules in src/lib/ontology/
// (the single source of truth) and re-run this script.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import {
  couplingEdges,
  digitalSystemsDomain,
  ontologyTiers,
  platformOntology,
  studiesEdges,
  type DigitalNode,
  type OntologyEntity,
  type OntologyTier,
  type PlatformModule,
} from "../src/lib/ontology";

function renderMembers(members: OntologyEntity[], depth = 0): string[] {
  const lines: string[] = [];
  const indent = "  ".repeat(depth);
  for (const member of members) {
    lines.push(`${indent}- ${member.label}`);
    if (member.children?.length) {
      lines.push(...renderMembers(member.children, depth + 1));
    }
  }
  return lines;
}

function renderTier(tier: OntologyTier): string {
  const lines: string[] = [];
  lines.push(`### ${tier.ordinal} — ${tier.name}`);
  lines.push("");
  lines.push(`- **Scale:** ${tier.rangeLabel}`);
  lines.push(`- **Platforms:** ${tier.platforms.join(", ")}`);
  lines.push("");
  lines.push(tier.principle);
  lines.push("");
  for (const group of tier.groups) {
    lines.push(`#### ${group.name}`);
    lines.push("");
    lines.push(...renderMembers(group.members));
    lines.push("");
  }
  return lines.join("\n");
}

function renderDigital(nodes: DigitalNode[], depth = 0): string[] {
  const lines: string[] = [];
  const indent = "  ".repeat(depth);
  for (const node of nodes) {
    lines.push(`${indent}- ${node.label}`);
    if (node.children?.length) {
      lines.push(...renderDigital(node.children, depth + 1));
    }
  }
  return lines;
}

function countEntities(members: OntologyEntity[]): number {
  return members.reduce(
    (n, m) => n + 1 + (m.children ? countEntities(m.children) : 0),
    0,
  );
}

function countDigital(nodes: DigitalNode[]): number {
  return nodes.reduce((n, d) => n + 1 + (d.children ? countDigital(d.children) : 0), 0);
}

function buildDoc(): string {
  const earthCount = ontologyTiers.reduce(
    (total, tier) => total + tier.groups.reduce((s, g) => s + countEntities(g.members), 0),
    0,
  );
  const digitalCount = countDigital(digitalSystemsDomain);

  const lines: string[] = [];

  lines.push(
    "<!-- AUTO-GENERATED by scripts/generate-ontology-doc.ts.",
    "     Do not edit by hand — edit src/lib/ontology/ and run `npm run gen:ontology`. -->",
    "",
    "# Sapiens Scientia Ontology",
    "",
    "The canonical model of the project, in three domains plus the relationships",
    "that connect them. Source: `src/lib/ontology/`.",
    "",
    `- **Earth Systems:** ${ontologyTiers.length} tiers · ${earthCount} systems`,
    `- **Sapiens Platforms:** ${platformOntology.length} platforms`,
    `- **Digital Systems:** ${digitalCount} systems`,
    `- **Relationships:** ${studiesEdges.length} studies edges · ${couplingEdges.length} couplings`,
    "",
    "## Earth Systems (Physical Earth)",
    "",
    "The five-tier nested-systems taxonomy, from elementary particles to the Sun.",
    "",
  );
  lines.push(...ontologyTiers.map(renderTier));

  lines.push("## Sapiens Platforms", "");
  lines.push("The interpretive lenses that read the Earth and Digital domains.", "");
  for (const platform of platformOntology) {
    lines.push(`### ${platform.name}`);
    lines.push("");
    lines.push(`- **Lens:** ${platform.label} — ${platform.domain}`);
    if (platform.modules.length) {
      const formatModule = (m: PlatformModule): string => {
        if (m.modules && m.modules.length > 0) {
          return `${m.name} (containing ${m.modules.map(formatModule).join(", ")})`;
        }
        return m.name;
      };
      lines.push(`- **Modules:** ${platform.modules.map(formatModule).join(", ")}`);
    }
    lines.push(
      `- **Studies (Earth):** ${platform.studies.earth.join(", ")}`,
      `- **Studies (Digital):** ${platform.studies.digital.join(", ")}`,
      "",
    );
  }

  lines.push("## Digital Systems (Digital Halo)", "");
  lines.push("Computation, communication, data, and intelligence systems.", "");
  lines.push(...renderDigital(digitalSystemsDomain));
  lines.push("");

  lines.push("## Relationships", "");
  lines.push("### Platform couplings", "");
  for (const edge of couplingEdges) {
    lines.push(`- **${edge.name}** (${edge.platforms.join(" ↔ ")}) — ${edge.detail}`);
  }
  lines.push("");

  return lines.join("\n") + "\n";
}

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "../docs/ONTOLOGY.md");
writeFileSync(outPath, buildDoc(), "utf-8");
console.log(`Wrote ${outPath}`);
